# Deploy gutenberg to fly.io

name: Fly deploy
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Enable corepack
        shell: bash
        run: corepack enable
      - name: install packages
        shell: bash
        run: yarn install
      - name: Checkout course material
        shell: bash
        run: yarn pullmat
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
          --build-arg DATABASE_URL=${{secrets.DATABASE_URL}}
          --build-arg NEXT_PUBLIC_PLAUSIBLE_DOMAIN=${{secrets.NEXT_PUBLIC_PLAUSIBLE_DOMAIN}}
          --wait-timeout 240
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
